global:
    scrape_interval: 5s

scrape_configs:
    - job_name: 'order'
      static_configs:
          - targets: ['order:3000']
    - job_name: 'product'
      static_configs:
          - targets: ['product:3001']
    - job_name: 'user'
      static_configs:
          - targets: ['user:3002']
    - job_name: 'db-exporter'
      static_configs:
          - targets: ['db-exporter:9216']

rule_files:
    - 'rules.yml'
